# Book settings
title: COSC 123
author: Firas Moosvi
logo: images/logo.jpg
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md","files/*"]
only_build_toc_files: true

bibtex_bibfiles:
  - about/citations.bib

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections : false
  baseurl : "https://firas.moosvi.com/courses/cosc123/2022_WT2/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis: false
    utterances:
      repo: "ubco-cmps/cosc123_course"
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

repository: 
  url          : https://github.com/ubco-cmps/cosc123_course
  path_to_book : ""
  branch       : main

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - substitution
    myst_substitutions:
      INSTRUCTOR: "Dr. Firas Moosvi (he/his/him)"
      PRONOUNCE: "[Fur-az Moose-vee](https://namedrop.io/firasmoosvi)"
      OFFICE: "SCI 393"
      PHONE: "N/A"
      COURSE_CODE: "COSC 123"
      SECTION: "001"
      CREDITS: "3"
      TITLE: "Computer Creativity"
      PREREQS: One of COSC 111, COSC 122.
      COREQS: N/A
      TERM: "2022 Winter Term 2"
      ROOM: "COM201"
      MEETING_TIMES: "Wednesday, Friday from 15:30 AM - 17:00 PM"
      GRACE_PERIOD: "48 hour"
      W_DATE_1: "11:59 PDT on January 23, 2023"
      W_DATE_2: "11:59 PDT on March 24, 2023"
      W_DATE_3: "March 24, 2023"
      EXAM_PERIOD: "Monday, April 17 - Friday, April 28"
      CANVAS_ID: "107665"
      CANVAS_LINK: "https://canvas.ubc.ca/courses/CANVAS_ID" # {{ '[course website]({link})'.format(link=CANVAS_LINK.replace('CANVAS_ID',CANVAS_ID)) }}
      ZOOM_LINK: "[Zoom](https://canvas.ubc.ca/courses/CANVAS_ID/external_tools/15408)"
      ANNOUNCEMENTS_LINK: "[Announcements](https://canvas.ubc.ca/courses/CANVAS_ID/announcements)"
      COURSE_LINK: "https://firas.moosvi.com/courses/cosc123/2022_WT2/"
      FORUM_LINK: "[Ed Discussion (sign up using your cwl@student.ubc.ca email here)](https://edstem.org/us/join/aEkgvZ)"
      ANALYTICS_OPTOUT: "[complete this form](https://ubc.ca1.qualtrics.com/jfe/form/SV_0p6lP4TtNpJn410)"
      FORMAT: "Lectures and Labs will all be running in-person in this course."
      ASSOCIATE_HEAD: "Yves Lucet [yves.lucet@ubc.ca](mailto:yves.lucet@ubc.ca)"
      ANON_FEEDBACK: "[feedback form](https://ubc.ca1.qualtrics.com/jfe/form/SV_0824TfIWX0twm5o?course=cosc123&term=2022_WT1)"
      TEXTBOOK: "We will not be needing a textbook for this course as you will be provided all the notes you need via the course website."