# Book settings
title: COSC 123
author: Firas Moosvi
logo: images/logo.jpg
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]
only_build_toc_files: true

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections : false
  baseurl : "https://firas.moosvi.com/courses/cosc123"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  google_analytics_id: UA-168693744-4 # add your Google Analytics Tracking Code
  comments:
    hypothesis: false
    utterances:
      repo: "ubco-cmps/cosc123_course"
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

launch_buttons:
  notebook_interface : "jupyterlab"
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository: 
  url          : https://github.com/ubco-cmps/cosc123_course
  path_to_book : ""
  branch       : master

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

    myst_substitutions:
      INSTRUCTOR: Dr. Firas Moosvi
      COURSE_CODE: COSC 123
      COURSE_TITLE: (3) Computer Creativity
      PREREQS: One of COSC 111, COSC 122.
      COREQS: N/A
      FEES: $0
      TERM: 2020 Winter Term 2
      W_DATE_1: 11:59 PDT on January 22, 2021 
      W_DATE_2: 11:59 PDT on March 26, 2021 
      W_DATE_3: 11:59 PDT on March 26, 2021
      CANVAS_ID: '64279'
      ED_ID: 7gqvVz
      LECTURE_TIMES: (Required) Fridays 14:00 - 15:00 PST; Monday/Wednesday 08:00 - 09:00 PST [Tutorial]
      ZOOM_LINK: "[Zoom](https://canvas.ubc.ca/courses/CANVAS_ID/external_tools/15408)"
      CU_LINK: "[Collaborate Ultra](https://canvas.ubc.ca/courses/CANVAS_ID/external_tools/5284)"
      ANNOUNCEMENTS_LINK: "[Canvas Announcements](https://canvas.ubc.ca/courses/CANVAS_ID/announcements)"
      COURSE_LINK: "https://firas.moosvi.com/courses/cosc123"
      FORUM_LINK: "[Ed Discussion](https://edstem.org/us/join/JOIN_LINK)"
      ANALYTICS_OPTOUT: "[complete this form](https://ubc.ca1.qualtrics.com/jfe/form/SV_4SB8DCF8fnktkLb)"

parse:
  myst_extended_syntax: true